<?php
namespace Digger\Icard\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function getBaseQueryBuilder()  
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select(array('a'))
            ->from('DiggerIcardGalleryBundle:Image', 'a')
        ;

        return $qb;
    }
}