services:
  gallery_main.menu_builder:
     class: Digger\Icard\GalleryBundle\Menu\MenuBuilder
     arguments: ["@knp_menu.factory"]
     
  gallery_main.menu.main:
      class: Knp\Menu\MenuItem # the service definition requires setting the class
      factory_service: gallery_main.menu_builder
      factory_method: createMainMenu
      arguments: ["@request","@security.context"]
      scope: request # needed as we have the request as a dependency here
      tags:
          - { name: knp_menu.menu, alias: main } # The alias is what is

  gallery_main.post_flush:
        class: Digger\Icard\GalleryBundle\EventListener\ImageListener
        tags:
            - { name: doctrine.event_listener, event: postFlush    } 
            - { name: doctrine.event_listener, event: postPersist  } 
            - { name: doctrine.event_listener, event: postUpdate   } 
            - { name: doctrine.event_listener, event: postRemove   }                      
            - { name: doctrine.event_listener, event: preRemove   }     
        arguments: [@service_container, @request_stack]