services:
  gallery_main.menu_builder:
     class: Digger\Icard\GalleryBundle\Menu\MenuBuilder
     arguments: ["@knp_menu.factory"]
     
  gallery_main.menu.main:
      class: Knp\Menu\MenuItem # the service definition requires setting the class
      factory_service: gallery_main.menu_builder
      factory_method: createMainMenu
      arguments: ["@request","@security.context"]
      scope: request # needed as we have the request as a dependency here
      tags:
          - { name: knp_menu.menu, alias: main } # The alias is what is

